name: Destroy API Gateway

on:
  push:
    branches:
      - develop
      - terraform-destroy
    paths:
      - 'api-gateway/**'

  pull_request:
    branches: ["*"]
    paths:
      - 'api-gateway/**'

permissions:
  id-token: write
  contents: read

jobs:
  Terraform_Plan_Destroy:
    name: Plan Destroy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Terraform CLI
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Run Plan Destroy
        uses: ./.github/workflows/workflow-lib-terraform.yml@develop  # ✅ FIXED THIS LINE
        with:
          aws-environment: dev
          terraform-project: api-gateway
          run-mode: plan

  Destroy_Lower_Environments:
    name: Destroy Non-Prod
    runs-on: ubuntu-latest
    needs: Terraform_Plan_Destroy
    strategy:
      matrix:
        aws-environments: [dev, qa]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Terraform CLI
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Destroy Non-Prod
        uses: ./.github/workflows/workflow-lib-terraform.yml@develop  # ✅ FIXED THIS LINE
        with:
          aws-environment: ${{ matrix.aws-environments }}
          terraform-project: api-gateway
          run-mode: destroy

  Destroy_Prod_Environments:
    name: Destroy Prod
    runs-on: ubuntu-latest
    needs: Destroy_Lower_Environments
    strategy:
      matrix:
        aws-environments: [uat, uat2, prod]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Terraform CLI
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Destroy Prod Environments
        uses: ./.github/workflows/workflow-lib-terraform.yml@develop  # ✅ FIXED THIS LINE
        with:
          aws-environment: ${{ matrix.aws-environments }}
          terraform-project: api-gateway
          run-mode: destroy
