name: Destroy API Gateway

on:
  push:
    branches:
      - develop
      - terraform-destroy
    paths:
      - 'api-gateway/**'

  pull_request:
    branches: ["*"]
    paths:
      - 'api-gateway/**'
permissions:
  id-token: write
  contents: read

jobs:
  Terraform_Plan_Destroy:
    name: Plan Destroy
    runs-on: ubuntu-latest
    steps:
    with:
      terraform_version: 1.5.7 
    name: Plan Destroy
    uses: ./.github/workflows/workflow-lib-terraform.yml
    with:
      aws-environment: dev
      terraform-project: api-gateway
      run-mode: plan

  Destroy_Lower_Environments:
    strategy:
      matrix:
        aws-environments: [dev, qa]
    name: Destroy Non-Prod
    needs: Terraform_Plan_Destroy
    uses: ./.github/workflows/workflow-lib-terraform.yml
    with:
      aws-environment: ${{ matrix.aws-environments }}
      terraform-project: api-gateway
      run-mode: destroy

  Destroy_Prod_Environments:
    strategy:
      matrix:
        aws-environments: [uat, uat2, prod]
    name: Destroy Prod
    needs: Destroy_Lower_Environments
    uses: ./.github/workflows/workflow-lib-terraform.yml
    with:
      aws-environment: ${{ matrix.aws-environments }}
      terraform-project: api-gateway
      run-mode: destroy
