name: Deploy CloudFront EU Dev

on:
  push:
    branches:
      - 'marcelsunche-cf-backend'

permissions:
  id-token: write
  contents: read

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
       role-to-assume: arn:aws:iam::541104114859:role/github-actions-role
       role-session-name: git-actions-deployment
       aws-region: eu-central-1
     
    - name: Terraform Init
      run: |
        cd cloudfront
        terraform init

    - name: Terraform Plan
      run: |
        cd cloudfront
        terraform plan -var-file=vars/dev.tfvars
    
    - name: Terraform Apply
      run: |
       cd cloudfront
       terraform apply -var-file=vars/dev.tfvars -auto-approve

    # - name: Terraform Destroy
    #   run: |
    #     cd cloudfront
    #     terraform destroy -var-file=vars/dev.tfvars -auto-approve
        
