name: Destroy CloudFront EU Dev

on:
  workflow_dispatch: # Allows manual trigger from GitHub Actions UI

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::541104114859:role/github-actions-role
        role-session-name: git-actions-deployment
        aws-region: eu-central-1

    - name: Terraform Init
      run: |
        cd cloudfront
        terraform init

    - name: Terraform Plan Destroy
      run: |
        cd cloudfront
        terraform plan -destroy -var-file=vars/dev.tfvars

    - name: Terraform Destroy
      run: |
        cd cloudfront
        terraform destroy -var-file=vars/dev.tfvars -auto-approve
