name: Deploy All Services

on:
  push:
    branches:
      - develop
    paths:
      - 'cloudfront/**'
      - 'elastic-beanstalk/**'
      - 'lambdas/**'
      - 'eventbridge/**'

  pull_request:
    branches: ["*"]
    paths:
      - 'cloudfront/**'
      - 'elastic-beanstalk/**'
      - 'lambdas/**'
      - 'eventbridge/**'

  workflow_dispatch:
    inputs:
      region:
        type: choice
        description: AWS region
        options:
          - eu-central-1
          - eu-west-2
      project:
        type: choice
        description: Terraform project to deploy or destroy
        options:
          - cloudfront
          - elastic-beanstalk
          - lambdas
          - eventbridge/schedulers
      action:
        type: choice
        description: Choose Terraform action (plan, apply, destroy)
        options:
          - plan
          - apply
          - destroy

permissions:
  id-token: write
  contents: read

env:
  terraform-projects:
    cloudfront: cloudfront
    elastic_beanstalk: elastic-beanstalk
    lambdas: lambdas
    eventbridge: eventbridge/schedulers

jobs:
  Terraform_Plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [cloudfront, elastic_beanstalk, lambdas, eventbridge]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::541104114859:role/github-actions-role
          role-session-name: git-actions-deployment
          aws-region: eu-central-1

      - name: Terraform Init
        run: |
          cd ${{ env.terraform-projects[matrix.project] }}
          terraform init

      - name: Terraform Plan
        run: |
          cd ${{ env.terraform-projects[matrix.project] }}
          terraform plan -var-file=vars/dev.tfvars

  Deploy_to_Lower_Environments:
    strategy:
      matrix:
        aws-environments: [dev, qa]
        project: [cloudfront, elastic_beanstalk, lambdas, eventbridge]
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' && inputs.action == 'apply' }}
    name: Non-prod Deploy
    needs: Terraform_Plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::541104114859:role/github-actions-role
          role-session-name: git-actions-deployment
          aws-region: ${{ inputs.region }}

      - name: Terraform Apply
        run: |
          cd ${{ env.terraform-projects[matrix.project] }}
          terraform apply -var-file=vars/${{ matrix.aws-environments }}.tfvars -auto-approve

  Deploy_to_Prod_Environments:
    strategy:
      matrix:
        aws-environments: [uat, uat2, prod]
        project: [cloudfront, elastic_beanstalk, lambdas, eventbridge]
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' && inputs.action == 'apply' }}
    name: Prod Deploy
    needs: Deploy_to_Lower_Environments
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::541104114859:role/github-actions-role
          role-session-name: git-actions-deployment
          aws-region: ${{ inputs.region }}

      - name: Terraform Apply
        run: |
          cd ${{ env.terraform-projects[matrix.project] }}
          terraform apply -var-file=vars/${{ matrix.aws-environments }}.tfvars -auto-approve

  Terraform_Destroy:
    strategy:
      matrix:
        aws-environments: [dev, qa, uat, uat2, prod]
        project: [cloudfront, elastic_beanstalk, lambdas, eventbridge]
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.action == 'destroy' }}
    name: Destroy Resources
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::541104114859:role/github-actions-role
          role-session-name: git-actions-destroy
          aws-region: ${{ inputs.region }}

      - name: Terraform Init
        run: |
          cd ${{ env.terraform-projects[matrix.project] }}
          terraform init

      - name: Terraform Destroy
        run: |
          cd ${{ env.terraform-projects[matrix.project] }}
          terraform destroy -var-file=vars/${{ matrix.aws-environments }}.tfvars -auto-approve
