name: Run Terraform Destroy

on:
  workflow_call:
    inputs:
      aws-environment:
        required: true
        type: string
      terraform-project:
        required: true
        type: string
      run-mode:
        required: false
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  Run_Terraform_Destroy:
    name: Run Terraform Destroy
    runs-on: ubuntu-latest
    environment: ${{ inputs.aws-environment }}
    outputs:
      result: ${{ join(steps.*.conclusion) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
           role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT }}:role/github-actions-role
           role-session-name: git-actions-deployment
           aws-region: eu-central-1

      - name: Display pre-destroy
        run: echo "${{ inputs.aws-environment }} ${{ vars.REGION }} ${{ inputs.terraform-project }} destroy"

      - name: Run Terraform Destroy
        run: |
          ./tf-init.sh ${{ inputs.aws-environment }} ${{ vars.REGION }} ${{ inputs.terraform-project }} destroy

  Check_Result:
    name: Check Result
    runs-on: ubuntu-latest
    needs: Run_Terraform_Destroy
    #if: contains(needs.Run_Terraform_Destroy.outputs.result, 'Error')
    steps:
      - run: echo "${{ needs.Run_Terraform_Destroy.outputs.result }}"
