trigger: none

pool:
  name: "CWH Sandbox BSRO"

variables:
  authorArtifactUrl: "https://dev.azure.com/BridgestoneGlobal/39785de8-4f00-4b0f-bb9c-d70ab9809232/_apis/build/builds/328818/artifacts?artifactName=dwdpkg-auth-artifacts&api-version=7.1&%24format=zip"
  publishArtifactUrl: "https://dev.azure.com/BridgestoneGlobal/39785de8-4f00-4b0f-bb9c-d70ab9809232/_apis/build/builds/328818/artifacts?artifactName=dwdpkg-pub-artifacts&api-version=7.1&%24format=zip"
  artifactFolder: "$(Pipeline.Workspace)/artifacts"

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- script: |
    echo "Creating artifacts folder..."
    mkdir -p "$(artifactFolder)"

    echo "Downloading Author Content artifact..."
    curl -L -o "$(artifactFolder)/dwdpkg-auth-artifacts.zip" "$(authorArtifactUrl)"

    echo "Downloading Publish Content artifact..."
    curl -L -o "$(artifactFolder)/dwdpkg-pub-artifacts.zip" "$(publishArtifactUrl)"
  displayName: "Download Artifacts"

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(artifactFolder)/dwdpkg-auth-artifacts.zip'
    artifact: 'AuthorContent'
    publishLocation: 'pipeline'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(artifactFolder)/dwdpkg-pub-artifacts.zip'
    artifact: 'PublishContent'
    publishLocation: 'pipeline'
