trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  ROOT_DIR: '$(Build.SourcesDirectory)'
  VARNISH_DIR: '$(Build.SourcesDirectory)/mnt/apps/varnish'
  QA_TESTS_DIR: '$(Build.SourcesDirectory)/qa-tests'
  OUT_DIR: '$(Build.ArtifactStagingDirectory)'

stages:
- stage: Build
  displayName: "Build & Package Varnish + QA tests"
  jobs:
  - job: Package
    steps:
    - checkout: self

    - script: |
        echo "Sources: $(Build.SourcesDirectory)"
        echo "Varnish dir: $(VARNISH_DIR)"
        echo "QA tests dir: $(QA_TESTS_DIR)"
        find "$(Build.SourcesDirectory)" -maxdepth 3 -type d -print
      displayName: "Debug: show repo structure"

    - task: Bash@3
      displayName: "Validate Varnish configs (*.vcl)"
      inputs:
        targetType: inline
        script: |
          set -euo pipefail
          if [ -d "$(VARNISH_DIR)" ]; then
            echo "Scanning $(VARNISH_DIR) for *.vcl ..."
            find "$(VARNISH_DIR)" -type f -name '*.vcl' -print
          else
            echo "No varnish directory found, skipping."
          fi

    - task: Bash@3
      displayName: "Validate QA test files (*.txt)"
      inputs:
        targetType: inline
        script: |
          set -euo pipefail
          if [ -d "$(QA_TESTS_DIR)" ]; then
            echo "Scanning $(QA_TESTS_DIR) for *.txt ..."
            find "$(QA_TESTS_DIR)" -maxdepth 1 -type f -name '*.txt' -print
          else
            echo "No qa-tests directory found, skipping."
          fi

    - task: CopyFiles@2
      displayName: "Stage Varnish configs"
      inputs:
        SourceFolder: '$(VARNISH_DIR)'
        Contents: '**/*.vcl'
        TargetFolder: '$(OUT_DIR)/varnish-configs'
        OverWrite: true
        flattenFolders: false
      continueOnError: true

    - task: CopyFiles@2
      displayName: "Stage QA test files"
      inputs:
        SourceFolder: '$(QA_TESTS_DIR)'
        Contents: '**/*.txt'
        TargetFolder: '$(OUT_DIR)/qa-tests'
        OverWrite: true
        flattenFolders: false
      continueOnError: true

    - task: ArchiveFiles@2
      displayName: "Archive varnish-configs.zip"
      inputs:
        rootFolderOrFile: '$(OUT_DIR)/varnish-configs'
        includeRootFolder: true
        archiveType: zip
        archiveFile: '$(OUT_DIR)/varnish-configs.zip'
        replaceExistingArchive: true
      continueOnError: true

    - task: ArchiveFiles@2
      displayName: "Archive qa-tests.zip"
      inputs:
        rootFolderOrFile: '$(OUT_DIR)/qa-tests'
        includeRootFolder: true
        archiveType: zip
        archiveFile: '$(OUT_DIR)/qa-tests.zip'
        replaceExistingArchive: true
      continueOnError: true

    - task: PublishBuildArtifacts@1
      displayName: "Publish build artifacts"
      inputs:
        PathtoPublish: '$(OUT_DIR)'
        ArtifactName: 'bsro-varnish-configs'
        publishLocation: 'Container'
