apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-read-only-binding
  namespace: dev-env
subjects:
  - kind: User
    name: shaheer
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: dev-read-only
  apiGroup: rbac.authorization.k8s.io