apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev-read-only
  namespace: dev-env
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "deployments"]
    verbs: ["get", "list", "watch"]
