apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
  namespace: mydata-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
        - name: mssql
          image: {{ .Values.image.mssql }}
          ports:
            - containerPort: {{ .Values.service.mssql.port }}
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              value: "{{ .Values.env.MSSQL_PASSWORD }}"
