apiVersion: v1
kind: Service
metadata:
  name: datafetch
  namespace: mydata-app
spec:
  type: {{ .Values.service.datafetch.type }}
  selector:
    app: datafetch
  ports:
    - protocol: TCP
      port: {{ .Values.service.datafetch.port }}
      targetPort: {{ .Values.service.datafetch.port }}
