apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: mydata-app
spec:
  type: {{ .Values.service.backend.type }}
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: {{ .Values.service.backend.port }}
      targetPort: {{ .Values.service.backend.port }}
