apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: mydata-app
spec:
  type: {{ .Values.service.frontend.type }}
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: {{ .Values.service.frontend.port }}
      targetPort: {{ .Values.service.frontend.port }}
